sanitize_267_download_refactor
gardener/gardenctl pull request #313
Opened 2020-09-15 07:00 UTC by tedteng

**What this PR does / why we need it**:
sanitize bash -c from download 
**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardenctl/issues/267

**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

2020-09-15 08:35 UTC, petersutter commented on pkg/cmd/download.go
> +				output, err := ExecCmdReturnOutput("kubectl", "--kubeconfig="+KUBECONFIG, "logs "+pod.Name+" -c "+"vpn-seed"+" -n "+shoot.Status.TechnicalID)
This does not work. Please properly pass the arguments to the function

2020-09-15 08:36 UTC, petersutter requested changes

2020-09-15 08:36 UTC, petersutter commented on pkg/cmd/download.go
> +				output, err := ExecCmdReturnOutput("kubectl", "--kubeconfig="+KUBECONFIG, "logs "+pod.Name+" -c "+"vpn-seed"+" -n "+shoot.Status.TechnicalID)
Same here, this does not work

2020-09-15 08:36 UTC, petersutter commented on pkg/cmd/download.go
> +				output, err := ExecCmdReturnOutput("kubectl", "--kubeconfig="+KUBECONFIG, "logs "+pod.Name+" -n "+"kube-system")
Same here, this does not work

2020-09-16 03:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/gardener/gardenctl?pullRequest=313) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/gardener/gardenctl?pullRequest=313) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/gardener/gardenctl?pullRequest=313) it.</sub>

2020-09-16 03:01 UTC, tedteng commented
all fixed

2020-09-16 07:32 UTC, petersutter approved these changes
/lgtm and much better, thank you

2020-09-16 23:45 UTC, neo-liang-sap commented
@tedteng please sign the CLA for this PR and all other your opening PRs.
besides please squash commits and i will proceed with merge

2020-09-17 07:15 UTC, petersutter commented
there seems to be an issue with the cla-assistant. 
> To trigger the recheck of a PR open `https://cla-assistant.io/check/{organisation}/{repo_name}?pullRequest={number}`. If successful you should be redirected to github. Sometimes it takes a moment but it should change to a green checkmark.

2020-09-21 14:14 UTC, merged