fix non unique shoot
gardener/gardenctl pull request #315
Opened 2020-09-15 07:53 UTC by tedteng

**What this PR does / why we need it**:
fix ssh target a non unque shoot name
**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardenctl/issues/312

**Special notes for your reviewer**:

**Release note**:

```improvement operator
fix ssh target 2 shoots with the same name in different projects
```

2020-09-15 08:01 UTC, tedteng commented
g = gardenctl
gg = go runtime for the fixing 

(⎈ |docker-desktop:default)➜  gardenctl git:(ssh_non_unique_shoot) gg ssh                                        
Nodes:
shoot--i333878--dev2-worker-w4iz0-z1-5748c9f988-jvfhf (Running)
(⎈ |docker-desktop:default)➜  gardenctl git:(ssh_non_unique_shoot) g ssh   
Error: stat /Users/i333878/.garden/cache/canary-virtual/seeds/gcp-eu2/kubeconfig.yaml: no such file or directory
(⎈ |docker-desktop:default)➜  gardenctl git:(ssh_non_unique_shoot)

2020-09-15 09:15 UTC, petersutter requested changes
I am aware that you did not introduce the `getSeedForProject` function in the first place, but it's always a good idea to take a closer look at the implementation and question it:

The `getSeedForProject` function is doing the required task overly complicated as it loops over all shoots across all namespace even though all the needed information is available on the target stack to efficiently fetch the targeted shoot to get the seed name.

Also the function name `getSeedForProject` is strange. A better name would be `getSeedForShoot` or just `getSeed`.

Take a look at the implementation of the `getTechnicalID` function that you are calling in this function. This function even fetches the shoot that you are interested in! From this shoot you can get the seedName and you are done. 

```go
func getTechnicalID() string {
	var target Target
	ReadTarget(pathTarget, &target)

	gardenClientset, err := target.GardenerClient()
	checkError(err)
	project, err := gardenClientset.CoreV1beta1().Projects().Get(target.Stack()[1].Name, metav1.GetOptions{})
	checkError(err)
	shoot, err := gardenClientset.CoreV1beta1().Shoots(*project.Spec.Namespace).Get(target.Stack()[2].Name, metav1.GetOptions{})
	checkError(err)
	return shoot.Status.TechnicalID
}
```

It would be nice if you would 
- factor out the getShoot-part from within `getTechnicalID` (which is basically most of the code from this function) and move it to it's own `getShoot` function.
- Then call the `getShoot` from `getTechnicalId`.
- And also call `getShoot` from the `getSeedForShoot`/`getSeed` function. 

Does this make sense?

2020-09-16 07:33 UTC, tedteng commented
> I am aware that you did not introduce the `getSeedForProject` function in the first place, but it's always a good idea to take a closer look at the implementation and question it:
> 
> The `getSeedForProject` function is doing the required task overly complicated as it loops over all shoots across all namespace even though all the needed information is available on the target stack to efficiently fetch the targeted shoot to get the seed name.
> 
> Also the function name `getSeedForProject` is strange. A better name would be `getSeedForShoot` or just `getSeed`.
> 
> Take a look at the implementation of the `getTechnicalID` function that you are calling in this function. This function even fetches the shoot that you are interested in! From this shoot you can get the seedName and you are done.
> 
> ```go
> func getTechnicalID() string {
> 	var target Target
> 	ReadTarget(pathTarget, &target)
> 
> 	gardenClientset, err := target.GardenerClient()
> 	checkError(err)
> 	project, err := gardenClientset.CoreV1beta1().Projects().Get(target.Stack()[1].Name, metav1.GetOptions{})
> 	checkError(err)
> 	shoot, err := gardenClientset.CoreV1beta1().Shoots(*project.Spec.Namespace).Get(target.Stack()[2].Name, metav1.GetOptions{})
> 	checkError(err)
> 	return shoot.Status.TechnicalID
> }
> ```
> 
> It would be nice if you would
> 
> * factor out the getShoot-part from within `getTechnicalID` (which is basically most of the code from this function) and move it to it's own `getShoot` function.
> * Then call the `getShoot` from `getTechnicalId`.
> * And also call `getShoot` from the `getSeedForShoot`/`getSeed` function.
> 
> Does this make sense?

done remove duplicate code

2020-09-16 08:26 UTC, petersutter commented
I guess this PR can be closed in favour of https://github.com/gardener/gardenctl/pull/317
I think #317 should fix the issue #312 , right?

2020-09-16 10:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/gardener/gardenctl?pullRequest=315) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/gardener/gardenctl?pullRequest=315) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/gardener/gardenctl?pullRequest=315) it.</sub>

2020-09-17 00:53 UTC, tedteng commented
> I guess this PR can be closed in favour of #317
> I think #317 should fix the issue #312 , right?

The https://github.com/gardener/gardenctl/issues/312 only fix the ssh bug same shoot name in different project,
when fetching shoot name from garden, it will only return the first shoot name entry from the garden even not in the correct project.  

https://github.com/gardener/gardenctl/pull/317 only refactor method technicalID, just in case any issue, in can be revoke without any impact.  So I spilt two different PRs

2020-09-17 01:17 UTC, tedteng commented
> I guess this PR can be closed in favour of #317
> I think #317 should fix the issue #312 , right?

nice point, I will check it.

2020-09-18 06:55 UTC, tedteng commented
/close as raised new PR https://github.com/gardener/gardenctl/pull/318

2020-09-18 06:55 UTC, closed without merging